defaults: 
  - model_defaults # Inherit model_defaults arguments

# --------------------------
#         Model
# --------------------------
model: 'cbm' # Model's name (to indicate it's a baseline)
tag: 'baseline' # Model's tag for wandb logging
concept_learning: 'embedding' # Concept Embedding Model baseline                

# --------------------------
#         Training
# --------------------------
training_mode: 'joint' # Optimization method of CEMs is joint training
embedding_size: 16 # Embedding size per concept for CEMs
